### ISSUE TITLE
Build instructions and environment setup

### ISSUE THREAD

**Issue by Bios-Marcel** [scribble-rs/ScribblersPad#17]
We need buildinstructions for all major systems.

**Comment by BigETI** [comment]
Anyone who works with Unity should know about this: https://docs.unity3d.com/Manual/BuildSettings.html

**Comment by Bios-Marcel** [comment]
Well ... that's not userfriendly onboarding ...

**Comment by BigETI** [comment]
I may add proper build instructions once this app is in beta.

**Comment by BigETI** [comment]
https://github.com/scribble-rs/ScribblersPad/wiki
