### ISSUE TITLE
Colorwheel too technical

### ISSUE THREAD

**Issue by Bios-Marcel** [scribble-rs/ScribblersPad#4]
A user will not understand that a lightness value of `0` means black, no matter which hue they chose. This needs to be simpler, but yet powerful.

Alternatively we could fall back to having predefined colors, like on the webclient and only offer the  color chooser as a "pro way" of doing it.

**Comment by BigETI** [comment]
What if the game prompts an easy color picker like we have on the web client, but then there is another button that opens a HSV color picker?

**Comment by Bios-Marcel** [comment]
Fine by me. Like the boxes on the webpage but in a "dialog", where the colorpicker is now.

**Comment by BigETI** [comment]
Another idea would be to have a layout like this:
![image](https://user-images.githubusercontent.com/4518424/108245849-11cefe80-7151-11eb-8e2b-4bc21c1d1f8d.png)

**Comment by Bios-Marcel** [comment]
thats better

**Comment by BigETI** [comment]
It looks like this right now:
![image](https://user-images.githubusercontent.com/4518424/108261707-46988100-7164-11eb-9cb7-d30828c544ac.png)

**Comment by Bios-Marcel** [comment]
Fancy. I showed this to someone and they weren't sure how to confirm their selection.
And I think the HSL thing is still confusing if it defaults to 0 brightness :thinking:

**Comment by BigETI** [comment]
I wonder if this is good enough for a color picker:

![image](https://user-images.githubusercontent.com/4518424/109671305-3fb23b00-7b74-11eb-8a1e-c728cdc948b4.png)

**Comment by Bios-Marcel** [comment]
I like it. However, I am planning on adding more colors, so the layout might change. But this is a minor detail. So far, it's good I think.
